### ISSUE TITLE
Suggestion and issues

### ISSUE THREAD

**Issue by NoozAbooz** [krishenriksen/onboarding#1]
Hello!
On the first slide, I propose the basics guide button open readme instead of the faq cuz the readme is filled with important info. The community support and get involved buttons lead to the discord channel on the server, which you need to join the discord to see, so I propose removing one button and make it link to the invite link for the server which is [https://discord.gg/Fh8sjmu](url). For the choose your theme section once you reboot, you won't be able to see the rest of it. There should be a slide saying to run the auto patcher, and also a button to run `sudo apt update` and `sudo apt upgrade`. The image on the last slide is broken. 
![image](https://user-images.githubusercontent.com/44128563/91214927-01255a80-e6d1-11ea-967a-38cfb2f632fd.png)

**Comment by krishenriksen** [comment]
fixed
